# Generated by Django 4.2.14 on 2024-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_invoice__past_dues_due"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="gst_amount",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="org_amount",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
