# Generated by Django 5.1 on 2024-08-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_receipt_gst_amount_alter_receipt_org_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="due",
            name="due_status",
            field=models.TextField(
                choices=[("Paid", "Paid"), ("Pending", "Pending")],
                default="Pending",
                max_length=255,
                verbose_name="Due Status",
            ),
        ),
    ]
