# Generated by Django 5.1 on 2024-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodel",
            name="course_duration",
            field=models.CharField(
                default=None,
                max_length=255,
                verbose_name="Course Duration (* In Minutes)",
            ),
        ),
    ]
