# Generated by Django 5.1 on 2024-08-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_coursemodel_course_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemodel",
            name="course_duration",
            field=models.CharField(
                default=None,
                max_length=255,
                verbose_name="Course Duration (* In Hours)",
            ),
        ),
    ]
