# Generated by Django 4.2.14 on 2024-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_student_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="m_name",
            field=models.CharField(
                default="", max_length=255, null=True, verbose_name="Mother Name"
            ),
        ),
    ]
