# Generated by Django 5.1 on 2024-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0005_auto_20240718_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_duration",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Exam Duration (In  Minutes)"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="contents",
            field=models.TextField(
                blank=True, null=True, verbose_name="Content (*Enter line by line)"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="duration",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Duration (*In Hours)"
            ),
        ),
    ]
