# Generated by Django 4.2.14 on 2024-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.FloatField()),
            ],
        ),
    ]
