# Generated by Django 4.2.14 on 2024-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0002_gst"),
    ]

    operations = [
        migrations.AddField(
            model_name="gst",
            name="gst_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]