# Generated by Django 4.2.14 on 2024-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0009_alter_studentenquirymodel_studying_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="m_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Mother Name"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="qualification",
            field=models.TextField(default="", verbose_name="Qualification"),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="qualification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Completed", "Completed"),
                    ("Undergoing", "Undergoing"),
                    ("others", "others"),
                ],
                default="Completed",
                max_length=50,
                null=True,
                verbose_name="Qualification Status",
            ),
        ),
    ]
