# Generated by Django 5.1 on 2024-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0010_enquiry_m_name_alter_enquiry_qualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenquirymodel",
            name="m_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Mother Name"
            ),
        ),
    ]
