# Generated by Django 5.1 on 2024-08-23 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0011_studentenquirymodel_m_name"),
        ("staffs", "0004_alter_staff_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="counsellor",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"status": "active"},
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="staffs.staff",
            ),
        ),
    ]
